services:
  - type: web
    name: karion-flow-api
    runtime: docker
    repo: https://github.com/Xafo/karion-flow
    region: ohio
    plan: free
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: R_ENVIRON
        value: ""
      - key: KARION_ANALISIS_DIR
        value: /data/analisis

  - type: web
    name: karion-flow-frontend
    runtime: static
    repo: https://github.com/Xafo/karion-flow
    buildCommand: ""
    staticPublishPath: ./frontend
    pullRequestPreviewsEnabled: false
    envVars:
      - key: API_URL
        value: https://karion-flow-api.onrender.com
